src/main/java/com/mycompany/masterrules/Controller/WnComboController.java
src/main/java/com/mycompany/masterrules/Controller/WnPaymentController.java
src/main/java/com/mycompany/masterrules/Controller/WnProductsController.java
src/main/resources/View/wnCombo.fxml
src/main/resources/View/wnPayment.fxml
src/main/resources/View/wnProducts.fxml

Agregación de winCombo, wnPayment, wnProducts y sus respectivos controllers

Cambio Vista

---

src/main/resources/View/wnProducts.fxml

Cambio wnProducts

---

.idea/dataSources.xml
src/main/java/com/mycompany/masterrules/Database/HibernateUtil.java
src/main/java/com/mycompany/masterrules/Model/Bill.java
src/main/java/com/mycompany/masterrules/Model/CashFlowReport.java
src/main/java/com/mycompany/masterrules/Model/CashRegisterAuditReport.java
src/main/java/com/mycompany/masterrules/Model/CashRegisterAuditReportManager.java
src/main/java/com/mycompany/masterrules/Model/Customer.java

Y modificado cositos de la base de datos

Cambiado de decimal a BigDecimal en algunas clases

---

.idea/git_toolbox_blame.xml
src/main/resources/View/wnProducts.fxml

Falta agregar los id a los componentes
*Nota: Checar bien cómo se van a nombrar

Cambios de diseño en wnProduct

---

src/main/java/com/mycompany/masterrules/Model/Employee.java
src/main/java/com/mycompany/masterrules/Model/UserAccount.java
src/main/java/com/mycompany/masterrules/Model/UserManager.java
src/main/java/com/mycompany/masterrules/Model/UserPermissions.java

Se agrega los de los Users y los Permissions, faltaria probar la gran cantidad de permisos que se tienen. Igualmente faltarian algunos metodos en UserManager debido a lo de la BD

Users and permissions

---

src/main/java/com/mycompany/masterrules/Controller/WnInventory.java
src/main/java/com/mycompany/masterrules/Controller/WnReports.java
src/main/java/com/mycompany/masterrules/Controller/WnUsersController.java
src/main/resources/View/wnCombo.fxml
src/main/resources/View/wnInventory.fxml
src/main/resources/View/wnReports.fxml
src/main/resources/View/wnUsers.fxml

Diseño grafico, falta hacerlo responsivo y nombrar las variables como en los criterios

wnInventory

---

src/main/java/com/mycompany/masterrules/Controller/ComboController.java
src/main/java/com/mycompany/masterrules/Controller/ProductController.java
src/main/java/com/mycompany/masterrules/Controller/WnSaleController.java
src/main/java/com/mycompany/masterrules/Model/Bill.java

Cambios que no rompen el codigo

---

src/main/java/com/mycompany/masterrules/Controller/ProductController.java
src/main/java/com/mycompany/masterrules/Model/CafeteriaManager.java
src/main/java/com/mycompany/masterrules/Model/CafeteriaMenu.java
src/main/java/com/mycompany/masterrules/Model/CafeteriaStorage.java
src/main/java/com/mycompany/masterrules/Model/Employee.java
src/main/java/com/mycompany/masterrules/Model/POSManager.java
src/main/java/com/mycompany/masterrules/Model/Product.java
src/main/java/com/mycompany/masterrules/Model/ProductQueries.java
src/main/java/com/mycompany/masterrules/Model/UserAccount.java
src/main/java/com/mycompany/masterrules/Model/UserManager.java
src/main/java/com/mycompany/masterrules/Model/UserPermissions.java

Se documento a forma de javadoc. También se hicieron correcciones: 
+algunos metodos se movieron para mejor organizacion, (no hubo cambio solo unos getters of setters estaban en otros lugares).
+se renombraron las variables de "modelo"(model) en ProductController y "permissionsStatus"(grantedPermissions) en UserPermissions por algo mas apropiado.
+isFoodTypeEmpty se le cambio el parametro "key" por un nombre más apropiado.
+se le cambio el nombre de metodo "getProducts" por "getProductsByType" porque no se describia bien el proposito de la original. 
+inicialize el valor de grantedPermissions en UserPermissions en el constructor en vez de su declaración.

Documentacion y modificacion de métodos y variables de todo lo relacionado a Products, Menu, Storage y Users

---

src/main/java/com/mycompany/masterrules/Model/UserManager.java

Modifique el metodo de isUsernameTaken para que tome como parámetro solo el nombre de usuario (username)

Modificacion a UserManager

---

src/main/java/com/mycompany/masterrules/Controller/ProductController.java
src/main/java/com/mycompany/masterrules/Model/CafeteriaManager.java
src/main/java/com/mycompany/masterrules/Model/CafeteriaMenu.java
src/main/java/com/mycompany/masterrules/Model/POSManager.java
src/main/java/com/mycompany/masterrules/Model/Product.java
src/main/java/com/mycompany/masterrules/Model/ProductQueries.java
src/test/java/DBAdminTest.java
src/test/java/ProductInventoryTest.java

El atributo ID del Product se cambio de un long a un string y se realizo cambios en varias partes del programa para acomodar a este nuevo tipo.
El atributo products del CafeteriaMenu cambio de ser hashmap a ser ArrayList con la finalidad de hacerlo más legible y se realizo varios cambios cambios a la clase para acomodarlo. También a aquellos metodos que se encargaban de buscar algun objeto (findProduct por ejemplo) se les cambio el parametro nombre al id del objeto, para evitar errores.

Modificacion del Menu y Product

---

src/main/java/com/mycompany/masterrules/Model/UserManager.java

Ya se realizaron las pruebas hacia UserManager y se realizaron modificaciones acorde a las pruebas

Modificaciones a UserManager

---

src/main/java/com/mycompany/masterrules/Model/CafeteriaManager.java
src/main/java/com/mycompany/masterrules/Model/CafeteriaMenu.java

Hice las pruebas para el menu y su manager, ya deberia funcionar bien.
Sin embargo, hubo casos especiales con el menu y storage (tomen en cuenta que ya fueron arreglados pero se requiere que entiendan la situación):
-AddProduct: El menu toma en cuenta el nombre del producto (para ver si no hay repetidos) y el storage toma en cuenta el stock (para ver si no es negativo). Ambos casos se encuentran separados uno del otro y como se guarda de manera secuencial (una despues de la otra) entonces lo que pasa es que se realiza uno  y no la otra cuando en realidad si ocurre un error en cualquiera de estos casos, no debe realizar el proceso de agregar a menu ni agregar a storage.
-EditProduct: es un problema parecido al anterior, para el inventario, el stock no debe ser negativo, pero ya en el caso …

Modificaciones a CafeteriaMenu y CafeteriaManager

---

src/main/java/com/mycompany/masterrules/App.java
src/main/java/com/mycompany/masterrules/Controller/WnCashRegisterAuditReport.java
src/main/java/com/mycompany/masterrules/Controller/WnInventoryController.java
src/main/java/com/mycompany/masterrules/Controller/WnPaymentController.java
src/main/java/com/mycompany/masterrules/Controller/WnReportsController.java
src/main/resources/com/mycompany/masterrules/wnCashRegisterAuditReport.fxml
src/main/resources/com/mycompany/masterrules/wnPayment.fxml
src/main/resources/com/mycompany/masterrules/wnReports.fxml

Vistas cambiadas:
CashRegisterAuditnoseque
Inventory
Payment
Reports
Junto con sus fxml
Se añadieron nombres de los componentes utilizados y por utilizar, se aplicaron los metodos a los botones de algunas vistas

Cambios en los controladores de las vistas

---

src/main/java/com/mycompany/masterrules/Model/POSManager.java
src/main/java/com/mycompany/masterrules/Model/UserAccount.java
src/main/java/com/mycompany/masterrules/Model/UserManager.java
src/main/java/com/mycompany/masterrules/Model/UserPermissions.java

Modifique el nombramiento de uno de los atributos en UserAccount y en algunos de los parametros ubicados en ciertos métodos. Además que acabe de traducir mi documentacion de ingles a español

Documentacion de lo relacionado a Users + Renombramiento de atributos y parametros

---

src/main/java/com/mycompany/masterrules/App.java
src/main/java/com/mycompany/masterrules/Controller/WnSideNavigationBar.java

VISTA intentos de q jale

---

src/main/resources/com/mycompany/masterrules/wnCashRegisterAuditReport.fxml
src/main/resources/com/mycompany/masterrules/wnCustomers.fxml
src/main/resources/com/mycompany/masterrules/wnInventory.fxml
src/main/resources/com/mycompany/masterrules/wnPayment.fxml
src/main/resources/com/mycompany/masterrules/wnSale.fxml
src/main/resources/com/mycompany/masterrules/wnUsers.fxml

VISTA intentos de q jale v2.0

---

src/main/resources/com/mycompany/masterrules/wnSale.fxml

VISTA intentos de q jale v2.1

---

src/main/java/com/mycompany/masterrules/Controller/WnSideNavigationBar.java

VISTA intentos de q jale v2.2

---

src/main/java/com/mycompany/masterrules/Controller/WnSaleController.java
src/main/resources/com/mycompany/masterrules/wnSale.fxml

VISTA intentos de q jale v2.3

---

src/main/java/com/mycompany/masterrules/Controller/wnLoginController.java

Intentos de que jale vista yq uede bien 3.4.5.1.2

---

src/main/java/com/mycompany/masterrules/Controller/WnCustomersController.java
src/main/java/com/mycompany/masterrules/Model/Customer.java
src/main/java/com/mycompany/masterrules/Model/CustomerAccount.java
src/main/java/com/mycompany/masterrules/Model/CustomerManager.java
src/main/java/com/mycompany/masterrules/Model/POSManager.java
src/main/resources/com/mycompany/masterrules/wnCustomers.fxml

Por fin, esta casi totalmente listo la parte de clientres

Torres actualizado

---

src/main/java/com/mycompany/masterrules/Controller/WnPaymentController.java
src/main/java/com/mycompany/masterrules/Controller/WnProductsController.java
src/main/resources/com/mycompany/masterrules/wnPayment.fxml
src/main/resources/com/mycompany/masterrules/wnProducts.fxml

Refactor DAOTemporal verification logic and enhance WnPaymentController with new visibility methods; update WnProductsController with additional UI components and event handlers.

IWUIWUIWUIWUWIUWIWUIWUIWUWIUWIU

---

src/main/java/com/mycompany/masterrules/Controller/WnCustomersController.java
src/main/java/com/mycompany/masterrules/Controller/WnSideNavigationBar.java
src/main/java/com/mycompany/masterrules/Model/CustomerManager.java
src/main/resources/com/mycompany/masterrules/wnCustomers.fxml

TOMAR NOTA YA QUE HAY CAMBIOS MUY IMPORTANTES.
Al principio estaba trabajando con los controller normalmente, pero terminé modificando el fxml de los customer para que no autoasigne el controlador correspondiente.  De esa forma podemos crear un constructor especial para que reciba el modelo y asi que todos los controllers que usen ese modelo puedan referencias especificamente la misma instancia.
De igual forma cambie la manera en la que se carga en la vista principal pues el pane como tal no puede acceder a su controlador por lo que primero lo hice load para asignar y ya luego lo cargué.
ADVERTENCIA: NO SUGIER QUITAR LA RUTA DEL CONTROLLADOR ASIGNADO HASTA QUE ESTÉ TOTALMENTE LISTO EL CONTROLLADOR YA QUE IDE COMO NETBEANS HACE LAS DECLARACIONES DE ATRIBUTOS AUTOMATICAMENTE GRACIAS AL FXML …

Cambios potentes

---

src/main/java/com/mycompany/masterrules/Controller/WnCashRegisterAuditReport.java
src/main/java/com/mycompany/masterrules/Controller/WnInventoryController.java
src/main/java/com/mycompany/masterrules/Controller/WnProductsController.java
src/main/java/com/mycompany/masterrules/Controller/WnSideNavigationBar.java
src/main/java/com/mycompany/masterrules/Controller/WnUsersController.java

ya tienen todos los controllers initializable

Intentos de que jale vista yq uede bien v 3.0

---

src/main/java/com/mycompany/masterrules/Controller/WnLoginController.java
src/main/resources/com/mycompany/masterrules/wnLogin.fxml

iwuiwuwiuwiwuiwuwiuwiuwi te amo rauuul jijijij :3

Add label for incorrect credentials in login view

---

src/main/java/com/mycompany/masterrules/Model/Login.java

Se modifico el metodo de validateUser para que sea más legible. Además, el if debe tener la situación o caso principal, así que se invirtió la condicion y sus respectivos comportamientos.

Modificacion de validateUser en Login

---

NOME FUNEN .md

WIUWIWUIWUIWUWIW TE AMO RAUL ESTOY ESTRESADA SI ME DICEN COSAS FEAS LLORO, ES MAS SI ME DICES COSAS LLORO

Create NOME FUNEN .md

---

src/main/java/com/mycompany/masterrules/Model/Combo.java
src/main/java/com/mycompany/masterrules/Model/CustomComboTemplate.java
src/main/java/com/mycompany/masterrules/Model/Customer.java
src/main/java/com/mycompany/masterrules/Model/CustomerAccount.java

iwuiwuwiuwiwuiwuwiuwiuwi te amo rauuul jijijij :3

RESEÑASSSSS v23.9 

---

src/main/java/com/mycompany/masterrules/Controller/WnProductsController.java
src/main/resources/com/mycompany/masterrules/wnProducts.fxml

Reverts jeusmateo/MasterRules#208

Revert "cambios y limpieza de codiguito jijij Refactor product registration method and update FXML for search functionality"

---

src/main/java/com/mycompany/masterrules/Controller/ItemCardProductController.java
src/main/java/com/mycompany/masterrules/Controller/WnCashRegisterAuditReportController.java
src/main/java/com/mycompany/masterrules/Controller/WnCustomersController.java
src/main/java/com/mycompany/masterrules/Controller/WnInventoryController.java
src/main/java/com/mycompany/masterrules/Controller/WnLoginController.java
src/main/java/com/mycompany/masterrules/Controller/WnPaymentController.java
src/main/java/com/mycompany/masterrules/Controller/WnReportsController.java
src/main/java/com/mycompany/masterrules/Controller/WnSaleController.java

organización codigo controller
